### ISSUE TITLE
Umlauts broken

### ISSUE THREAD

**Issue by larskluge** [larskluge/node-inkpad#1]
The Inkpad https://www.inkpad.io/JKnXqaNeCG contains German umlauts. 

Downloading the content via cli: 

```
inkpad JKnXqaNeCG.md
```

Results in broken umlauts: 

https://www.dropbox.com/s/fkk5vw3wloajgu7/Screenshot%202015-01-29%2014.19.31.png?dl=0

Probably UTF8 encoding doesn't go all the way through.

**Comment by mondoreale** [comment]
Hi Lars, it was inkpad's bug which I just fixed. Please try your command again. :)

**Comment by larskluge** [comment]
Oh, that's super interesting! Can you link the commit here please? Wanna have a look ;-) Curious now!

**Comment by mondoreale** [comment]
[Here you go](https://github.com/larskluge/inkpad/commit/7d4153649a0888b585a192c277a39f89845158c6). :)

**Comment by mondoreale** [comment]
Not that interesting tho, really. :P

**Comment by larskluge** [comment]
Oh, haha, yeah, that's a good one! :neckbeard:
